include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: error
    include_file_not_found: ignore
linter:
  rules:
    - avoid_function_literals_in_foreach_calls
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_final_locals
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_typing_uninitialized_variables
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_statements
